# -*- coding: utf-8 -*-
"""Processamento Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_V-au9DqnRrXsbUOSVNBkwYKR1NPlprk

# Criação da pasta para o armazenamento dosdados das pastas zipadas
"""

import os
import zipfile
import pandas as pd
import re
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

zip_files = [
    '/content/C001_1870mAh-20260416T000208Z-3-001.zip',
    '/content/C002_1804mAh-20260416T000208Z-3-001.zip',
    '/content/C003_1320mAh-20260416T000210Z-3-001.zip',
    '/content/C004_990mAh-20260416T000212Z-3-001.zip',
    '/content/C005_530mAh-20260416T000214Z-3-001.zip',
    '/content/C006_490mAh-20260416T000216Z-3-001.zip'
]

extract_base = 'dados'

os.makedirs(extract_base, exist_ok=True)

for i, zip_path in enumerate(zip_files):
    pasta_destino = os.path.join(extract_base, f'celula_{i+1}')

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(pasta_destino)

"""# Leitura dos dados e concatenação em um Dataset único"""

dfs = []

for root, dirs, files in os.walk(extract_base):
    for file in files:
        if file.endswith('.csv'):
            caminho = os.path.join(root, file)
            print(caminho)

            df = pd.read_csv(caminho)

            if 'celula_1' in caminho:
                df['cell_id'] = 1
            elif 'celula_2' in caminho:
                df['cell_id'] = 2
            elif 'celula_3' in caminho:
                df['cell_id'] = 3
            elif 'celula_4' in caminho:
                df['cell_id'] = 4
            elif 'celula_5' in caminho:
                df['cell_id'] = 5
            elif 'celula_6' in caminho:
                df['cell_id'] = 6

            dfs.append(df)

# juntar tudo
df_final = pd.concat(dfs, ignore_index=True)

df_final.head()

df_final['DATE'] = pd.to_datetime(
    df_final['DATE'],
    format='%Y-%m-%d_%H:%M:%S',
    errors='coerce'
)

df_final.head()

"""# Gerando a coluna SOC no meu Dataset concatenado"""

df_final.head()

#===============================
# 1. CONVERTER DATA
# ===============================
df_final['DATE'] = pd.to_datetime(
    df_final['DATE'],
    format='%Y-%m-%d_%H:%M:%S',
    errors='coerce'
)

df_final = df_final.dropna(subset=['DATE'])

df_final = df_final.sort_values(['cell_id', 'DATE']).reset_index(drop=True)
# ===============================
# 2. DETECTAR CICLOS (POR VOLTAGEM - ROBUSTO)
# ===============================

# diferença de tensão entre pontos consecutivos
df_final['voltage_diff'] = df_final.groupby('cell_id')['VOLTAGE(V)'].diff()

# detectar salto grande de tensão (reset do ciclo)
df_final['novo_ciclo'] = (df_final['voltage_diff'] > 0.7).astype(int)

# garantir que o primeiro ponto de cada célula é ciclo 0
df_final['novo_ciclo'] = df_final['novo_ciclo'].fillna(0)

# criar ID do ciclo
df_final['cycle_id'] = df_final.groupby('cell_id')['novo_ciclo'].cumsum()

print("Total de ciclos detectados:", df_final['cycle_id'].max())

# ===============================
# 3. CALCULAR DELTA DE TEMPO
# ===============================
df_final['delta_t'] = df_final.groupby('cell_id')['DATE'].diff().dt.total_seconds()
df_final['delta_t'] = df_final['delta_t'].fillna(0)

# converter para horas
df_final['delta_t_h'] = df_final['delta_t'] / 3600

# tempo acumulado POR CICLO
df_final['tempo_acumulado'] = df_final.groupby(['cell_id', 'cycle_id'])['delta_t'].cumsum()

# ===============================
# 4. GARANTIR CAPACIDADE EM Ah
# ===============================
mapa_capacidade = {
    1: 1.870,
    2: 1.804,
    3: 1.320,
    4: 0.990,
    5: 0.530,
    6: 0.490
}

df_final['capacidade_ah'] = df_final['cell_id'].map(mapa_capacidade)

df_final['capacidade_ah'] = (
    df_final['capacidade_ah'] / 1000
    if df_final['capacidade_ah'].max() > 10
    else df_final['capacidade_ah']
)

# ===============================
# 5. CALCULAR SOC POR CICLO (COM NORMALIZAÇÃO)
# ===============================
def calcular_soc(grupo):
    capacidade = grupo['capacidade_ah'].iloc[0]

    # Coulomb Counting
    grupo['delta_soc'] = (-grupo['CURRENT(A)'] * grupo['delta_t_h']) / capacidade

    # SOC bruto
    grupo['SOC'] = 1 - grupo['delta_soc'].cumsum()

    # 🔥 NORMALIZAÇÃO (ESSENCIAL)
    soc_max = grupo['SOC'].max()
    soc_min = grupo['SOC'].min()

    # evitar divisão por zero
    if soc_max != soc_min:
        grupo['SOC'] = (grupo['SOC'] - soc_min) / (soc_max - soc_min)
    else:
        grupo['SOC'] = 0  # ciclo degenerado

    return grupo

df_final = df_final.groupby(['cell_id', 'cycle_id'], group_keys=False).apply(calcular_soc)

# ===============================
# 6. LIMITAR SOC
# ===============================
df_final['SOC'] = df_final['SOC'].clip(0, 1)

# ===============================
# DEBUG
# ===============================
df_final[['cell_id', 'VOLTAGE(V)', 'cycle_id']].head(100)

df_final.groupby(['cell_id', 'cycle_id']).agg({
    'SOC': ['min', 'max'],
    'VOLTAGE(V)': ['min', 'max'],
    'delta_t': 'count'
})

"""# Verificar um Ciclo"""

df_final.rename(columns={"RESISTANCE(Ω)": "RESISTANCE"}, inplace=True)
df_final.rename(columns={"NTC_TEMP(℃)": "NTC_TEMP"}, inplace=True)
df_final.rename(columns={"VOLTAGE(V)": "VOLTAGE"}, inplace=True)
df_final.rename(columns={"CURRENT(A)": "CURRENT"}, inplace=True)
df_final.rename(columns={"POWER(W)": "POWER"}, inplace=True)


df_ciclo = df_final[
    (df_final['cell_id'] == 1) &
    (df_final['cycle_id'] == 2)
]

df_ciclo.head(50)

import matplotlib.pyplot as plt

for cell in df_final['cell_id'].unique():
    df_cell = df_final[df_final['cell_id'] == cell]

    for ciclo in df_cell['cycle_id'].unique():
        df_ciclo = df_cell[df_cell['cycle_id'] == ciclo]

        plt.figure()
        plt.plot(df_ciclo['tempo_acumulado'], df_ciclo['VOLTAGE'])

        plt.title(f'Célula {cell} - Ciclo {ciclo}')
        plt.xlabel('Tempo (s)')
        plt.ylabel('Voltgem')

        plt.tight_layout()
        plt.show()

"""# Treinamento de RL

A ideia é dividir a célula em seus ciclos e treinar/testar com elas mesmas
"""

!pip install stable-baselines3[extra]
!pip install gymnasium

df_final.head()

import gymnasium as gym
from gymnasium import spaces
import numpy as np
import pandas as pd

class BatteryEnv(gym.Env):

    def __init__(self, df):
        super(BatteryEnv, self).__init__()

        self.df = df
        self.current_step = 0

        # Features
        self.features = [
            'VOLTAGE',
            'CURRENT',
            'POWER',
            'RESISTANCE',
            'NTC_TEMP'
        ]

        # Espaço de estados
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(len(self.features),),
            dtype=np.float32
        )

        # Ação = SOC estimado
        self.action_space = spaces.Box(
            low=0.0,
            high=100.0,
            shape=(1,),
            dtype=np.float32
        )

    def reset(self, seed=None, options=None):
        self.current_step = 0

        obs = self.df.loc[self.current_step, self.features].values.astype(np.float32)

        return obs, {}

    def step(self, action):

        soc_real = self.df.loc[self.current_step, 'SOC']

        soc_pred = action[0]

        # Reward
        reward = -((soc_real - soc_pred) ** 2)

        self.current_step += 1

        done = self.current_step >= len(self.df) - 1

        if not done:
            obs = self.df.loc[self.current_step, self.features].values.astype(np.float32)
        else:
            obs = np.zeros(len(self.features), dtype=np.float32)

        return obs, reward, done, False, {}

"""## Divisão das células para treinamento e teste"""

train_df = (
    df_final[df_final['cell_id'] == 1]
    .sort_values('DATE')
    .reset_index(drop=True)
)

test_df = (
    df_final[df_final['cell_id'] == 2]
    .sort_values('DATE')
    .reset_index(drop=True)
)

train_df.head()

test_df.head()

#Treinamento em uma célula

train_env = BatteryEnv(train_df)

model = PPO("MlpPolicy", train_env, verbose=1)

model.learn(total_timesteps=10000)


# #treinamento do PPO

# from stable_baselines3 import PPO

# env = BatteryEnv(df_final)

# model = PPO(
#     "MlpPolicy",
#     env,
#     verbose=1
# )

# model.learn(total_timesteps=10)

#avaliar em outra célula

test_env = BatteryEnv(test_df)

obs, _ = test_env.reset()

done = False

preds = []
reals = []

while not done:

    action, _ = model.predict(obs)

    obs, reward, done, _, _ = test_env.step(action)

    preds.append(action[0])

    reals.append(
        test_df.loc[test_env.current_step - 1, 'SOC']
    )

#Predição
# obs, _ = env.reset()

# done = False

# while not done:

#     action, _ = model.predict(obs)

#     obs, reward, done, _, _ = env.step(action)

#     print("SOC previsto:", action[0])

from sklearn.metrics import mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(reals, preds))

print("RMSE:", rmse)

"""# Teste LSTM

Justificar com maior número de dados melhor o resultado
"""

from sklearn.preprocessing import MinMaxScaler
!pip install tensorflow

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

"""## Treinando com 1 bateria e testando com 5"""

import random

# células disponíveis
cells = [1, 2, 3, 4, 5, 6]

# sorteia uma para teste
train_cell = random.choice(cells)

# restantes para teste
test_cells = [c for c in cells if c != train_cell]

print("TRAIN CELL:", train_cell)
print("TEST CELLS:", test_cells)

train_df = (
    df_final[df_final['cell_id'] == train_cell]
    .sort_values(['cell_id', 'DATE'])
    .reset_index(drop=True)
)

test_df = (
    df_final[df_final['cell_id'].isin(test_cells)]
    .sort_values(['cell_id', 'DATE'])
    .reset_index(drop=True)
)

features = [
  'VOLTAGE',
  'CURRENT',
  'POWER',
  'RESISTANCE',
  'NTC_TEMP'
]

target = 'SOC'

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

train_df[features] = scaler_X.fit_transform(train_df[features])

train_df[[target]] = scaler_y.fit_transform(train_df[[target]])

test_df[features] = scaler_X.transform(test_df[features])

test_df[[target]] = scaler_y.transform(test_df[[target]])

import numpy as np

def create_sequences(df, features, target, seq_size=20):

    X = []
    y = []

    for cell in df['cell_id'].unique():

        cell_df = df[df['cell_id'] == cell]

        data = cell_df[features].values
        target_data = cell_df[target].values

        for i in range(seq_size, len(cell_df)):

            X.append(data[i-seq_size:i])

            y.append(target_data[i])

    return np.array(X), np.array(y)

X_train, y_train = create_sequences(
    train_df,
    features,
    target,
    seq_size=20
)

X_test, y_test = create_sequences(
    test_df,
    features,
    target,
    seq_size=20
)



model = Sequential([

    LSTM(
        64,
        return_sequences=True,
        input_shape=(X_train.shape[1], X_train.shape[2])
    ),

    Dropout(0.2),

    LSTM(32),

    Dropout(0.2),

    Dense(1)
])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test),
    shuffle=False
)

y_pred = model.predict(X_test)

y_test_real = scaler_y.inverse_transform(
    y_test.reshape(-1, 1)
)

y_pred_real = scaler_y.inverse_transform(y_pred)

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        y_test_real,
        y_pred_real
    )
)

print("RMSE:", rmse)

"""## Treinando com 3 e testando com 3"""

import random

# células disponíveis
cells = [1, 2, 3, 4, 5, 6]

# sorteia 3 para treino
train_cells = random.sample(cells, 3)

# restantes para teste
test_cells = [c for c in cells if c not in train_cells]

print("TRAIN CELLS:", train_cells)
print("TEST CELLS:", test_cells)

train_df = (
    df_final[df_final['cell_id'].isin(train_cells)]
    .sort_values(['cell_id', 'DATE'])
    .reset_index(drop=True)
)

test_df = (
    df_final[df_final['cell_id'].isin(test_cells)]
    .sort_values(['cell_id', 'DATE'])
    .reset_index(drop=True)
)

features = [
  'VOLTAGE',
  'CURRENT',
  'POWER',
  'RESISTANCE',
  'NTC_TEMP'
]

target = 'SOC'

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

train_df[features] = scaler_X.fit_transform(train_df[features])

train_df[[target]] = scaler_y.fit_transform(train_df[[target]])

test_df[features] = scaler_X.transform(test_df[features])

test_df[[target]] = scaler_y.transform(test_df[[target]])

import numpy as np

def create_sequences(df, features, target, seq_size=20):

    X = []
    y = []

    for cell in df['cell_id'].unique():

        cell_df = df[df['cell_id'] == cell]

        data = cell_df[features].values
        target_data = cell_df[target].values

        for i in range(seq_size, len(cell_df)):

            X.append(data[i-seq_size:i])

            y.append(target_data[i])

    return np.array(X), np.array(y)

X_train, y_train = create_sequences(
    train_df,
    features,
    target,
    seq_size=20
)

X_test, y_test = create_sequences(
    test_df,
    features,
    target,
    seq_size=20
)

model = Sequential([

    LSTM(
        64,
        return_sequences=True,
        input_shape=(X_train.shape[1], X_train.shape[2])
    ),

    Dropout(0.2),

    LSTM(32),

    Dropout(0.2),

    Dense(1)
])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test),
    shuffle=False
)

y_pred = model.predict(X_test)

y_test_real = scaler_y.inverse_transform(
    y_test.reshape(-1, 1)
)

y_pred_real = scaler_y.inverse_transform(y_pred)

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        y_test_real,
        y_pred_real
    )
)

print("RMSE:", rmse)

"""
## Treinando com 5 baterias e testando com 1"""

import random

# células disponíveis
cells = [1, 2, 3, 4, 5, 6]

# sorteia uma para teste
test_cell = random.choice(cells)

# restantes para treino
train_cells = [c for c in cells if c != test_cell]

print("TEST CELL:", test_cell)
print("TRAIN CELLS:", train_cells)

train_df = (
    df_final[df_final['cell_id'].isin(train_cells)]
    .sort_values(['cell_id', 'DATE'])
    .reset_index(drop=True)
)

test_df = (
    df_final[df_final['cell_id'] == test_cell]
    .sort_values('DATE')
    .reset_index(drop=True)
)

features = [
  'VOLTAGE',
  'CURRENT',
  'POWER',
  'RESISTANCE',
  'NTC_TEMP'
]

target = 'SOC'

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

train_df[features] = scaler_X.fit_transform(train_df[features])

train_df[[target]] = scaler_y.fit_transform(train_df[[target]])

test_df[features] = scaler_X.transform(test_df[features])

test_df[[target]] = scaler_y.transform(test_df[[target]])

import numpy as np

def create_sequences(df, features, target, seq_size=20):

    X = []
    y = []

    for cell in df['cell_id'].unique():

        cell_df = df[df['cell_id'] == cell]

        data = cell_df[features].values
        target_data = cell_df[target].values

        for i in range(seq_size, len(cell_df)):

            X.append(data[i-seq_size:i])

            y.append(target_data[i])

    return np.array(X), np.array(y)

X_train, y_train = create_sequences(
    train_df,
    features,
    target,
    seq_size=20
)

X_test, y_test = create_sequences(
    test_df,
    features,
    target,
    seq_size=20
)

!pip install tensorflow

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential([

    LSTM(
        64,
        return_sequences=True,
        input_shape=(X_train.shape[1], X_train.shape[2])
    ),

    Dropout(0.2),

    LSTM(32),

    Dropout(0.2),

    Dense(1)
])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test),
    shuffle=False
)

y_pred = model.predict(X_test)

y_test_real = scaler_y.inverse_transform(
    y_test.reshape(-1, 1)
)

y_pred_real = scaler_y.inverse_transform(y_pred)

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

import numpy as np

rmse = np.sqrt(
    mean_squared_error(
        y_test_real,
        y_pred_real
    )
)

print("RMSE:", rmse)

"""Teste de RL -

#
"""
